version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/application:cached
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx:/var/log/nginx:delegated
    depends_on:
      - php

  php:
    build:
      context: .
    image: caloriary:latest
    volumes:
      - .:/application:cached
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=caloriary"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: ""
      DATABASE_HOST: "mysql"
    entrypoint: ["sh", "/wait-for-db.sh"]
    command: ["php-fpm"]
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "caloriary"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
